# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/python/runtime
# for details.

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables: 
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://root:root@/surfing_weather?unix_socket=/cloudsql/surfs-up-enp:us-east4:hawaii-weather


beta_settings:
  cloud_sql_instances: surfs-up-enp:us-east4:hawaii-weather
